export { ProjectNameInput } from './ProjectNameInput'
export { ProjectAdminInput } from './ProjectAdminInput'
export { ProjectDescriptionInput } from './ProjectDescriptionInput'
export { ProjectCategoryInput } from './ProjectCategotyInput'
export { ProjectImageInput } from './ProjectImageInput'
export { ProjectImpactLocationInput } from './ProjectImpactLocationInput'
export { ProjectBankAccountInput } from './ProjectBankAccountInput'
